server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

app:
  jwtSecret: JWTSuperSecretKeyJWTSuperSecretKeyJWTSuperSecretKeyJWTSuperSecretKey
  jwtExpirationInMs: 604800000

spring:
  data:
    mongodb:
      database: test
      host: localhost
      port: 27017
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
          lowerCaseServiceId: true
      routes:
        - id: battle-sim-service
          uri: lb://battle-sim-service
          predicates:
            - Path=/battlesim/**
          filters:
            - RewritePath=/battlesim/(?<endpoint>.*), /$\{endpoint}
        #            - AddResponseHeader=Access-Control-Allow-Origin, *
        - id: gatewayix
          uri: lb://gatewayix
          predicates:
            - Path=/auth/{segment}
          filters:
            - SetPath=/{segment}
      #            - AddResponseHeader=Access-Control-Allow-Origin, *
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
            - GET
            - PUT
            - POST
            - DELETE
            - OPTIONS
            allowedHeaders: "*"

#logging:
#  level:
#    root: TRACE