#!/bin/sh
sudo service mongod start &
cd /home/ec2-user/repos/yomenik/build/backend
/usr/java/jdk-12.0.2/bin/java -jar -Dspring.profiles.active=native cloudconfig.jar &
sleep 10
cd ../frontend
sudo yarn install &
sleep 30
yarn start &
