spring:
  jpa:
    show-sql: true
  #    hibernate:
#      ddl-auto: create
#  datasource:
#    url: jdbc:mysql://localhost:3306/test?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=CET
#    username: user
#    password: user
  data:
    mongodb:
      database: test
      host: localhost
      port: 27017
logging:
  level:
    root: info

app:
  jwtSecret: JWTSuperSecretKeyJWTSuperSecretKeyJWTSuperSecretKeyJWTSuperSecretKey
  jwtExpirationInMs: 604800000
