#!/bin/sh
service mongod start
java -jar cloudconfig.jar
sleep 5
java -jar eurekson.jar
sleep 5
java -jar gatewayix.jar
sleep 5
java -jar user-service.jar
sleep 5
java -jar battlesim-service.jar
sleep 5

