spring:
  data:
    mongodb:
      database: test
      host: localhost
      port: 27017
logging:
  level:
    root: info

app:
  jwtSecret: JWTSuperSecretKeyJWTSuperSecretKeyJWTSuperSecretKeyJWTSuperSecretKey
  jwtExpirationInMs: 604800000
