spring:
  cloud:
    discovery:
      enabled: false
    config:
      enabled: false
      discovery:
        enabled: false
  data:
    mongodb:
      database: test
      host: localhost
      port: 27017
logging:
  level:
    root: info