POST http://localhost:8080/shiptravel
Accept: */*
Content-Type: application/json
Cache-Control: no-cache
PRINCIPAL-ID: 1

{
  "planetIdFrom": 1,
  "planetIdTo": 2,
  "fleet": {
    "shipsLevel1": 5,
    "shipsLevel3": 2
  },
  "missonType": "attack"
}

###

