POST http://localhost:8080/shiptravel
Accept: */*
Content-Type: application/json
Cache-Control: no-cache
PRINCIPAL-ID: 1

{
  "planetIdFrom": 1,
  "planetIdTo": 2,
  "fleet": {
    "SHIP_LEVEL1_template": 50,
    "SHIP_LEVEL3_template": 2
  },
  "missonType": "attack"
}

###

