POST http://{{host}}/fleet_management/ship_template
Accept: */*
Content-Type: application/json
Cache-Control: no-cache
PRINCIPAL-ID: 1

{
  "templateName": "testTemplate2",
  "hullType": "SHIP_LEVEL1",
  "weaponSlots": {
    "1": "LASER1"
  },
  "fireMode": "SCATTER"
}

###

